### ISSUE TITLE
Modifier l'affichage des intérêts dans la modal de détails

### ISSUE THREAD

**Issue by romthi38** [PnEcrins/GeoSites#27]
Il faut faire comme pour les documents pdf et créer un fichier php de génération du json afin d'afficher les intérêts liés à un site.

**Comment by gildeluermoz** [comment]
done ! cf 3260f8171aceef37e27ed114af50cad8bdb5e0ff and 3260f8171aceef37e27ed114af50cad8bdb5e0ff
