### ISSUE TITLE
Interaction carte liste - le rouge reste allumé quand on choisi un autre site dans la liste

### ISSUE THREAD

**Issue by gildeluermoz** [PnEcrins/GeoSites#31]
Quand on choisi un site sur la carte, il s'allume en rouge dans la liste mais si dans la foulée on choisi un site dans la liste, le site en rouge reste rouge

**Comment by romthi38** [comment]
Je viens de corriger, est-ce que ça marche maintenant ?

**Comment by gildeluermoz** [comment]
Attention, je travail sur ces fichiers 

```
Gil DELUERMOZ 
```

Chargé de mission développement web et bases de données 

Parc national des Écrins 
Tél : +33 (0) 4 92 40 20 38 (lundi et mardi) 
+33 (0)4 92 21 08 49 (mercredi et jeudi matin) 
www.ecrins-parcnational.fr 
----- Mail original -----

De: "romthi38" notifications@github.com 
À: "PnEcrins/GeoSiteApp" GeoSiteApp@noreply.github.com 
Cc: "gildeluermoz" gil.deluermoz@ecrins-parcnational.fr 
Envoyé: Jeudi 11 Février 2016 13:49:48 
Objet: Re: [GeoSiteApp] Interaction carte liste - le rouge reste allumé quand on choisi un autre site dans la liste (#31) 

Closed #31 .

**Comment by gildeluermoz** [comment]
Le soucis d'incohérence n'est pas corrigé
