### ISSUE TITLE
Mise en place d'un système de filtrage

### ISSUE THREAD

**Issue by romthi38** [PnEcrins/GeoSites#4]
## A faire

Mettre quelque part dans la sidebar un système de filtrage sur les éléments de la couche.

Piste à suivre : le filtre sur [ng-mapCreator-fp](https://github.com/PnCevennes/ng-mapCreator-fp)

**Comment by camillemonchicourt** [comment]
Oui mais je les mettrai plutôt juste au dessus de la liste, sous le petit texte d'intro.

**Comment by romthi38** [comment]
Faire comme sur [ng-mapCreator-fp](https://github.com/PnCevennes/ng-mapCreator-fp) ? C'est-à-dire mettre les options de filtrage dans un dropdown ?

**Comment by camillemonchicourt** [comment]
Non juste mettre une ou 2 listes déroulantes au dessus de la liste des résultats

**Comment by gildeluermoz** [comment]
closed by c22003885f34df521aa3e395cd26e441e0c105e8
