### ISSUE TITLE
Revoir la conf et la doc

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoSites#44]
Le fichier `dbconnect.php.sample` n'est plus utile.
Pas mal de paramètres sont dans `/data/htmlContent.json`. Les mettre dans un dossier de config ou au moins créer une version sample, faire le gitignore et le mentionner dans la doc.

**Comment by gildeluermoz** [comment]
closed by 59732acafc5d546597f0e50bd32d86bf367df240
