### ISSUE TITLE
AngularJS et SEO

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoSites#45]
Actuellement l'application ne dispose que d'une URL, du coup le contenu des fiches ne sera pas référencé par les moteurs de recherche. 
Une alternative à cela semble être pushState - http://www.ocpsoft.org/java/seo-friendly-angularjs-with-html5-pushstate-rewrite-and-twelve-lines-of-code/

Il y a d'autres trucs à creuser pour être sur que les moteurs de recherche arrivent bien à accéder au contenu des pages, pas visible directement avec AngularJS - https://www.searchenginejournal.com/warning-youre-killing-seo-efforts-using-angular-js/142031/

http://www.angularonrails.com/get-html5-pushstate-working-angular-rails/

**Comment by gildeluermoz** [comment]
Voir comment charger une modale via un lien avec href mais sans provoquer le rechargement de la page. Ceci fonctionne : http://geologie.ecrins-parcnational.fr/site-PAC0004

**Comment by camillemonchicourt** [comment]
En cherchant "angularjs specific url for modal" sur Google.
J'ai trouvé ça qui propose des solutions et indique d'autres liens avec de l'info sur le sujet https://lingohub.com/blog/2015/06/bootstrap-modal-window-custom-url-angularjs/

Voir aussi les autres résultats sur Google.

**Comment by camillemonchicourt** [comment]
De plus nous venons de faire en sorte que chaque modale ait son propre title.
