### ISSUE TITLE
ajouter un bouton "+" dans les collapses de la modal détail

### ISSUE THREAD

**Issue by gildeluermoz** [PnEcrins/GeoSites#47]

**Comment by camillemonchicourt** [comment]
Et un "-" quand une accordéon est ouvert. 

Peut-être sous forme de bouton pour être bien visible. http://images.google.fr/imgres?imgurl=http%3A%2F%2Fi.stack.imgur.com%2FOIIst.png&imgrefurl=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F26149593%2Fhow-to-use-css-to-modify-an-icon-with-the-bootstrap-collapse&h=381&w=499&tbnid=Uujrsl0-JlzDOM%3A&docid=hALiMcStA7CgLM&ei=TmHVVvz0EMS0afT7s8gK&tbm=isch&iact=rc&uact=3&dur=13095&page=1&start=0&ndsp=50&ved=0ahUKEwj805Lglp_LAhVEWhoKHfT9DKkQrQMIJDAC

Ou on utilise souvent une flèche vers la droite ou vers le bas.
http://images.google.fr/imgres?imgurl=http%3A%2F%2Fi.stack.imgur.com%2FOIIst.png&imgrefurl=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F26149593%2Fhow-to-use-css-to-modify-an-icon-with-the-bootstrap-collapse&h=381&w=499&tbnid=Uujrsl0-JlzDOM%3A&docid=hALiMcStA7CgLM&ei=TmHVVvz0EMS0afT7s8gK&tbm=isch&iact=rc&uact=3&dur=13095&page=1&start=0&ndsp=50&ved=0ahUKEwj805Lglp_LAhVEWhoKHfT9DKkQrQMIJDAC

**Comment by gildeluermoz** [comment]
J'ai mis une flèche type carret plus grosse.
Closed by 0e6648c4a71c2df1e4421dd10c9777306f506cd6

**Comment by camillemonchicourt** [comment]
Tooltip au survol ? Genre "Afficher / Masquer"
