### ISSUE TITLE
Afficher limite du parc

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoSites#53]
Pour bien voir le territoire concerné par l'inventaire.
Nommer Territoire et pas Parc pour être générique.
Tuiles MBTILES ou geojson ? GeoJson surement bien plus lourd à charger

**Comment by gildeluermoz** [comment]
si on a le mbtiles de rando écrins ce sera plus simple. On peut aussi mettre un geojson en fichier mais il faut le simplifier et réduire le nombre de sommet pour des questions de perf.
Camille je te laisse me fournir la source.
