### ISSUE TITLE
Régler problème de collapse en lien avec le scroll

### ISSUE THREAD

**Issue by romthi38** [PnEcrins/GeoSites#6]
Régler problème de collapse en lien avec le scroll.
LOrsque l'on clique sur un marqueur ça scroll bien sur le site dans la liste mais le site ne s'ouvre pas.
Voir code commenté qui si on l'active, ouvre la div mais elle ne se referme pas si on ouvre un autre site.

**Comment by romthi38** [comment]
Etant donné que nous avons décidé de ne plus faire de collapse ouverts automatiquement dans la liste, ce bug n'a plus lieu d'être.

A fermer ?

**Comment by gildeluermoz** [comment]
oui on ferme le ticket et on ouvrira un nouveau si on souhaite changer le comportement actuel
