### ISSUE TITLE
Virer /config/config.js ?

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoSites#60]
Pour ne garder que le sample ?

**Comment by gildeluermoz** [comment]
C'est déjà fait ! Non ?

**Comment by camillemonchicourt** [comment]
Le fichier est sur le Github

**Comment by gildeluermoz** [comment]
ben non !

**Comment by camillemonchicourt** [comment]
OK je me suis embrouillé, ce que je voulais dire c'est que ce fichier n'a plus l'air d'être utilisé ?
