### ISSUE TITLE
Ajouter GOOGLE ANALYTICS

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoSites#65]
Avec en paramètre le clé GA.
Si paramètre vide, alors je n'intègre pas le JS de Google Analytics.
Nécessite un module AngularJS ?
Voir exemple Geotrek-rando - https://github.com/makinacorpus/Geotrek-rando/search?utf8=%E2%9C%93&q=analytics

**Comment by RaphaelChochon** [comment]
Salut salut,
Et pourquoi pas Piwik plutôt que GA ? C'est du libre, auto hébergé, c'est pas Google mais c'est tout aussi fiable au niveau des résultats !
Reste à voir pour l'intégrer a Angular puisque c'est du singlepage donc moins évident...
A creuser : https://github.com/angulartics?utf8=%E2%9C%93&query=piwik

**Comment by camillemonchicourt** [comment]
Oui en effet Piwik est tout aussi bien et évite Google. 
Merci pour les liens, on va creuser ça.

**Comment by RaphaelChochon** [comment]
Je vais également essayer de l'intégrer dans le portail carto que nous développons au PNM.
Pour nous l’installation de Piwik est faite depuis quelques jours ;)
