### ISSUE TITLE
Sites sensibles

### ISSUE THREAD

**Issue by gildeluermoz** [PnEcrins/GeoSites#7]
S'assurer que les sites sensibles sont exclus de la vue permetttant la création du geojson

**Comment by romthi38** [comment]
Ne sont affichés que les sites suivants : public ou réservé.
A voir avec Cedric si on affiche les réservés.

**Comment by gildeluermoz** [comment]
Oui faire le point avec Cédric.
Pour info, de mémoire, initialement le PNE a produit 200 fiches. 
Combien de sites la base contient-elle, tout statut confondu ?

**Comment by romthi38** [comment]
J'ai 425 fichiers pdf, il y a tous les sites de PACA mais pas Rhône Alpes.
Il y a 71 sites dans la base, mais pas de sites confidentiels.

**Comment by gildeluermoz** [comment]
Ok. On garde que les sites publics et on n'affiche pas les sites réservés.
