### ISSUE TITLE
Modale - Ouvrir, fermer, ouvrir

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/GeoSites#71]
Je viens d'identifier un bug sur les modales. 

Si j'ouvre une modale, puis la ferme puis essaie de rouvrir la même modale, celle-ci ne s'ouvre pas.

**Comment by gildeluermoz** [comment]
T'avais qu'à pas la fermer !

**Comment by camillemonchicourt** [comment]
:-)

**Comment by camillemonchicourt** [comment]
Retour ATOL CD : 

Les modales ne fonctionnent effectivement pas si on clique en dehors d'elle. Si on les ferme avec "x" en haut à droite ou le bouton "Fermer" (qui sont bindés sur `ok()` de `modalDetailsController.js`) , le comportement attendu est le bon.

De ce que je comprends de la [doc](https://angular-ui.github.io/bootstrap/#/modal), il faudrait écouter l'évent `modal.closing` du scope de la modale pour y exécuter les opérations qui nous intéressent (`$location.path('/'); $rootScope.pageTitle = '';`) et retirer ses opérations de "ok()".

A vue de nez et sans test, dans `modalDetailsController.js`, cela donnerait :

```
$scope.ok = function () {
  $uibModalInstance.close();
};

$scope.$on('modal.closing', function(){
  $location.path('/');
  $rootScope.pageTitle = '';
});
```
