### ISSUE TITLE
Griser les sites absents de la carte

### ISSUE THREAD

**Issue by gildeluermoz** [PnEcrins/GeoSites#8]
Lorsque l'on zoome sur la carte, les sites qui sont absents de la carte s'estompent dans la liste. Trouver un style css qui les estompent et l'événement leaflet à utiliser pour qu'à chaque action de zoom et dézoom une fonction qui recalcule l'affichage de la liste se déclanche.

**Comment by gildeluermoz** [comment]
Fait mais par cohérence on fait le choix de masquer les éléments plutôt que de les griser.

**Comment by camillemonchicourt** [comment]
OK super !
