### ISSUE TITLE
REORGANSATION DU CODE - créer des templates

### ISSUE THREAD

**Issue by gildeluermoz** [PnEcrins/GeoSites#9]
Au moins un template pour la liste à gauche. 
Un template pour la popup de détails du site.
Un template pour les filtres (futurs).

**Comment by romthi38** [comment]
J'ai fais des directives Angular déjà pour tout ça, c'est donc déjà sous forme de template.

**Comment by gildeluermoz** [comment]
Je parle de template html 
ça par exemple
https://github.com/PnEcrins/GeoSiteApp/blob/master/index.php#L60-L89
Tu peux le mettre dans un template et dans l'index tu mets juste une div qu'angular va appeler.

**Comment by romthi38** [comment]
Ok, je vois !
Ce sera fait.

**Comment by gildeluermoz** [comment]
pense a fermer les tickets lorsque tu estimes que le travail est fait. On peut toujours recréer des tickets si bug ou complément à corriger/apporter.
